import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.argv[2]).href),root=path.resolve(import.meta.dirname,'..');
const server=http.createServer((req,res)=>{const uri=new URL(req.url,'http://local').pathname,file=path.resolve(root,'.'+(uri==='/'?'/index.html':decodeURIComponent(uri)));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(fs.readFileSync(file));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath:process.argv[3],headless:true}),evidence=path.join(root,'artifacts/goal-media-budget');fs.mkdirSync(evidence,{recursive:true});
let cases=0;
try{
 for(const width of [1440,390])for(const finish of ['porcelain-cream','midnight-black']){
  const context=await browser.newContext({viewport:{width,height:900}});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.waitForFunction(()=>!!window.HANI_GOAL_PROGRESS);
  await page.evaluate(finish=>{unlockLoginGate();showView('settings');document.documentElement.dataset.finish=finish;document.body.dataset.finishActive='true';state.ledgerMonths=[{month:today().slice(0,7),targetT:1000000}];state.goalRegistry=[];window.before=JSON.stringify(state);window.localBefore=JSON.stringify({...localStorage});window.localWrites=[];const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(this===localStorage)window.localWrites.push(k);return set.call(this,k,v)};window.saveCalls=0;window.failSave=false;save=()=>{window.saveCalls++;return {ok:!window.failSave}};dataHubInvalidate=()=>{};dataHubRefresh=()=>{};renderGoalRegistry();},finish);
  const form=page.locator('#goalRegistryForm'),metric=form.locator('[name=metric_id]'),value=form.locator('[name=value]'),preview=page.locator('#goalRegistryPreview');
  await metric.selectOption('spending_jispi_krw');assert.match(await page.locator('#goalBudgetSuggestion').innerText(),/15%/);await page.locator('#goalBudgetUseSuggestion').click();assert.equal(await value.inputValue(),'1150000');
  assert.deepEqual(await page.evaluate(()=>({same:JSON.stringify(state)===window.before,calls:window.saveCalls,writes:window.localWrites})),{same:true,calls:0,writes:[]});
  await form.locator('[name=year]').fill('2027');await form.locator('[name=year]').dispatchEvent('change');await form.locator('[name=quarter]').selectOption('1');await form.locator('[type=submit]').click();await page.locator('#goalRegistryCancel').click();assert.equal(await page.evaluate(()=>JSON.stringify(state)===window.before),true);
  await metric.selectOption('media_watched_count');assert.equal(await value.getAttribute('step'),'1');assert.match(await page.locator('#goalBudgetSuggestion').innerText(),/1件|1건/);await value.fill('12');await form.locator('[type=submit]').click();assert.match(await preview.innerText(),/시청 작품 수/);assert.match(await preview.innerText(),/12 편/);assert.equal(await page.evaluate(()=>window.saveCalls),0);
  await value.fill('13');await value.dispatchEvent('change');assert.equal(await page.locator('#goalRegistryApprove').count(),0,'changed input invalidates stale Preview');assert.equal(await page.evaluate(()=>goalRegistryDraft===null),true);await value.fill('12');await value.dispatchEvent('change');await form.locator('[type=submit]').click();
  await page.locator('#goalRegistryPanel').screenshot({path:path.join(evidence,`${width}-${finish}.png`),style:'.ui26-top,#haniContextRemote,.hani-remote-mobile-trigger{visibility:hidden!important}'});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.ok(await page.locator('#goalRegistryPanel').evaluate(e=>e.scrollWidth<=e.clientWidth+1));
  await page.evaluate(()=>window.oldApprove=document.getElementById('goalRegistryApprove'));await page.locator('#goalRegistryApprove').click();await page.evaluate(()=>window.oldApprove.click());
  const result=await page.evaluate(()=>({calls:window.saveCalls,goal:state.goalRegistry[0],otherSame:JSON.stringify({...state,goalRegistry:[]})===window.before}));assert.equal(result.calls,1);assert.equal(result.goal.metric_id,'media_watched_count');assert.equal(result.goal.value,12);assert.equal(result.goal.unit,'title');assert.equal(result.otherSame,true);
  // Existing handler rollback with a synthetic failing save, no protected storage access.
  await metric.selectOption('media_watched_count');await form.locator('[name=year]').fill('2028');await form.locator('[name=year]').dispatchEvent('change');await form.locator('[name=quarter]').selectOption('1');await value.fill('15');await page.evaluate(()=>{window.failSave=true;window.beforeFail=JSON.stringify(state)});await form.locator('[type=submit]').click();await page.locator('#goalRegistryApprove').click();assert.match(await preview.innerText(),/저장에 실패/);assert.equal(await page.evaluate(()=>JSON.stringify(state)===window.beforeFail),true);
  await metric.selectOption('body_bmi');await value.fill('25');await form.locator('[type=submit]').click();assert.match(await preview.innerText(),/BMI/);await page.locator('#goalRegistryCancel').click();
  await page.evaluate(()=>{state.ledgerMonths=[]});await metric.selectOption('spending_jispi_krw');assert.equal(await page.locator('#goalBudgetUseSuggestion').count(),0);assert.match(await page.locator('#goalBudgetSuggestion').innerText(),/없습니다/);
  assert.deepEqual(await page.evaluate(()=>({same:JSON.stringify({...localStorage})===window.localBefore,writes:window.localWrites})),{same:true,writes:[]});assert.deepEqual(errors,[]);cases++;await context.close();
 }
 // One fresh disposable context exercises the unchanged real protected save path.
 const real=await browser.newContext();await real.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const p=await real.newPage();await p.goto(origin);await p.waitForFunction(()=>!!window.HANI_GOAL_PROGRESS);
 await p.evaluate(()=>{unlockLoginGate();showView('settings');state.goalRegistry=[];state.unknownFutureField={kept:true};window.otherBefore=JSON.stringify({...state,goalRegistry:null,meta:null});window.protectedWrites=0;const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(this===localStorage&&k===STORAGE_KEY)window.protectedWrites++;return set.call(this,k,v)};renderGoalRegistry()});
 const f=p.locator('#goalRegistryForm');await f.locator('[name=metric_id]').selectOption('media_watched_count');await f.locator('[name=year]').fill('2027');await f.locator('[name=year]').dispatchEvent('change');await f.locator('[name=quarter]').selectOption('1');await f.locator('[name=value]').fill('10');await f.locator('[type=submit]').click();assert.equal(await p.evaluate(()=>window.protectedWrites),0);await p.locator('#goalRegistryApprove').click();
 const saved=await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));return {writes:window.protectedWrites,goals:s.goalRegistry.map(g=>({metric:g.metric_id,value:g.value,unit:g.unit})),kept:s.unknownFutureField.kept,otherSame:JSON.stringify({...s,goalRegistry:null,meta:null})===window.otherBefore}});
 assert.deepEqual(saved,{writes:1,goals:[{metric:'media_watched_count',value:10,unit:'title'}],kept:true,otherSame:true});await real.close();
 console.log(`PASS ${cases} real-app synthetic combinations: +15% input-only/cancel, media Preview/approval once/rollback, BMI regression, missing reference, desktop/mobile overflow; localStorage writes 0 in stub cases. Additional real protected save: Preview writes 0, approved writes 1, saved goal read-back and unknown/other fields preserved. Cloud/production unverified.`);
}finally{await browser.close();await new Promise(r=>server.close(r));}
