import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import {fileURLToPath,pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.argv[2]).href),root=fileURLToPath(new URL('../',import.meta.url));
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost'),file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':decodeURIComponent(url.pathname)));if(!file.startsWith(root)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(fs.readFileSync(file))});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:process.argv[3],headless:true});
try{for(const width of [1440,390]){
 const context=await browser.newContext({viewport:{width,height:800}});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);
 await page.evaluate(()=>{unlockLoginGate();showView('reading');window.navigationBeforeState=JSON.stringify(state);window.navigationRaw=localStorage.getItem('hani_os_life_v23');window.navigationWrites=[];const old=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){window.navigationWrites.push(k);return old.call(this,k,v)};document.querySelector('#bookTitle').value='저장하지 않은 임시 제목'});await page.waitForTimeout(350);await page.evaluate(()=>window.scrollTo({top:350,behavior:'instant'}));await page.waitForTimeout(250);
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('hani_os_navigation_v1')));assert.equal(saved.view,'reading');assert(saved.y>100,JSON.stringify(await page.evaluate(()=>({width:innerWidth,y:scrollY,height:document.documentElement.scrollHeight,body:document.body.scrollHeight,main:document.querySelector('main').scrollHeight,boot:navigationBooted,saved:navigationRead(),locked:loginGateUnlocked}))));assert.deepEqual(Object.keys(saved).sort(),['version','view','y']);assert(!JSON.stringify(saved).includes('임시 제목'));
 assert.deepEqual(await page.evaluate(()=>({state:JSON.stringify(state)===window.navigationBeforeState,raw:localStorage.getItem('hani_os_life_v23')===window.navigationRaw,keys:[...new Set(window.navigationWrites)]})),{state:true,raw:true,keys:['hani_os_navigation_v1']});
 await page.goto(origin);await page.evaluate(()=>unlockLoginGate());await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>document.body.dataset.view),'reading');assert(await page.evaluate(()=>scrollY)>100);
 await page.goto(origin+'/index.html#movie');await page.evaluate(()=>unlockLoginGate());await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>document.body.dataset.view),'movie');assert.equal(await page.evaluate(()=>scrollY),0);
 await page.evaluate(()=>{lockLoginGate();localStorage.setItem('hani_os_navigation_v1',JSON.stringify({version:1,view:'deployment',y:999,token:'never-read'}))});await page.goto(origin);assert.equal(await page.evaluate(()=>document.body.dataset.view),'home');
 await page.evaluate(()=>{localStorage.setItem('hani_os_navigation_v1','{broken')});await page.goto(origin);assert.equal(await page.evaluate(()=>document.body.dataset.view),'home');
 await page.evaluate(()=>{unlockLoginGate();const old=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw Error('synthetic storage unavailable')};showView('movie');window.scrollTo(0,100);Storage.prototype.setItem=old});assert.equal(await page.evaluate(()=>document.body.dataset.view),'movie');assert.deepEqual(errors,[]);await context.close();
}console.log('PASS navigation 1440/390: last view and scroll after reopen, explicit hash wins, malformed/excluded view safe fallback, storage failure usable, UI metadata only, protected data/state unchanged. Draft persistence and Android unverified.');}finally{await browser.close();await new Promise(r=>server.close(r))}
