const assert=require("node:assert/strict");
const fs=require("node:fs");
const http=require("node:http");
const path=require("node:path");
const {chromium}=require("playwright");

const root=path.resolve(__dirname,"..");
const types={".html":"text/html; charset=utf-8",".js":"text/javascript",".css":"text/css",".png":"image/png",".jpg":"image/jpeg",".webp":"image/webp"};
const server=http.createServer((request,response)=>{const pathname=decodeURIComponent(new URL(request.url,"http://local").pathname),file=path.resolve(root,"."+(pathname==="/"?"/index.html":pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){response.writeHead(404);response.end();return}response.writeHead(200,{"Content-Type":types[path.extname(file)]||"application/octet-stream","Cache-Control":"no-store"});fs.createReadStream(file).pipe(response)});
const intersects=(a,b)=>a&&b&&a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top;

(async()=>{await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,executablePath:process.env.HANI_CHROME_PATH||"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"});try{const context=await browser.newContext({viewport:{width:390,height:844}});await context.route("**/*",route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());await context.addInitScript(()=>{localStorage.hani_os_gate_session_v2="1"});const page=await context.newPage(),errors=[];page.on("pageerror",error=>errors.push(String(error)));await page.goto(origin,{waitUntil:"load"});await page.waitForFunction(()=>typeof showView==="function"&&document.querySelector(".hani-remote-mobile-trigger"));await page.evaluate(()=>{unlockLoginGate();showView("intake");toast("겹침 확인")});await page.waitForFunction(()=>document.querySelector(".hani-remote-mobile-trigger")?.classList.contains("is-intake-inline")&&document.querySelector("#toast")?.classList.contains("show"));const layout=await page.evaluate(()=>{const box=selector=>{const rect=document.querySelector(selector)?.getBoundingClientRect();return rect?{left:rect.left,right:rect.right,top:rect.top,bottom:rect.bottom,width:rect.width,height:rect.height}:null};const trigger=document.querySelector(".hani-remote-mobile-trigger");return {trigger:box(".hani-remote-mobile-trigger"),composer:box(".yuna-composer"),toast:box("#toast"),position:getComputedStyle(trigger).position,inline:trigger.classList.contains("is-intake-inline"),overflow:document.documentElement.scrollWidth-window.innerWidth}});assert.equal(layout.inline,true);assert.equal(layout.position,"static");assert.equal(intersects(layout.trigger,layout.composer),false,"Remote trigger must not cover the YUNA composer/send area");assert.equal(intersects(layout.trigger,layout.toast),false,"Remote trigger must not cover toast feedback");assert.ok(layout.overflow<=1,`mobile horizontal overflow: ${layout.overflow}`);assert.deepEqual(errors,[]);await context.close();console.log("PASS: 390px YUNA Remote trigger is inline and does not overlap composer or toast.")}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}})().catch(error=>{console.error(error);process.exitCode=1});
