import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import {fileURLToPath,pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.argv[2]).href);
const root=fileURLToPath(new URL('../',import.meta.url));
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(fs.readFileSync(file))});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath:process.argv[3],headless:true});fs.mkdirSync(path.join(root,'artifacts/report-common'),{recursive:true});
try{for(const width of [1440,390])for(const finish of ['porcelain-cream','midnight-black']){
 const context=await browser.newContext({viewport:{width,height:900}});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.waitForFunction(()=>!!window.HANI_GOAL_PROGRESS?.renderReport);
 await page.evaluate(finish=>{unlockLoginGate();showView('monthlyReport');document.documentElement.dataset.finish=finish;document.body.dataset.finishActive='true';monthlyReportBoard='quarterly';monthlyReportRenderBoard()},finish);
 const host=page.locator('#quarterGoalReport');assert.match(await host.innerText(),/원본 검증 대기/);assert.equal(await host.locator('article').count(),0);
 await page.evaluate(()=>{window.originalContext=goalPeriodReadContext;window.allowed=true;window.beforeState=JSON.stringify(state);window.beforeLocal=JSON.stringify({...localStorage});window.writes=[];const old=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(this===localStorage)window.writes.push(k);return old.call(this,k,v)};window.fixture={books:[{id:'b',status:'read',completedDate:'2026-09-03'}],movies:[{status:'watched',watchedDate:'2026-09-04'}],exercise:[{date:'2026-09-05',steps:9000}],body:[{date:'2026-09-06',weight:80,bmi:27}],learningQuizzes:[{status:'completed',completedAt:'2026-09-02T00:00:00Z',total:30,correctCount:15}],investmentBrokerSnapshots:[],ledgerMonths:[{month:'2026-09',items:[{date:'2026-09-01',category:'variable',amount:100}]}],goalRegistry:[{goal_id:'bmi',revision:1,metric_id:'body_bmi',goal_type:'quarter',year:2026,quarter:3,value:25,unit:'kg/m²',semantics:'point_target',effective_from:'2026-07-01',effective_to:'2026-09-30',created_at:'2026-07-01T00:00:00+09:00',status:'active'}]};goalPeriodReadContext=()=>window.allowed?{source:structuredClone(window.fixture),asOf:'2026-09-30',evaluationAt:'2026-10-07T00:00:00Z',canonical:{brokerTotal:()=>0,ledgerSpending:r=>r.items.reduce((s,x)=>s+x.amount,0)}}:null;window.HANI_GOAL_PROGRESS.renderReport()});
 await host.locator('[data-report-year]').fill('2026');await host.locator('[data-report-year]').dispatchEvent('change');await host.locator('[data-report-quarter]').selectOption('3');assert.equal(await host.locator('article').count(),9);const bmi=host.locator('article').filter({has:page.locator('h4',{hasText:/^BMI$/})});assert.match(await bmi.innerText(),/실적 27/);assert.match(await bmi.innerText(),/목표 25/);
 const equal=await page.evaluate(()=>{const facts=window.HANI_GOAL_PROGRESS.read({type:'month',year:2026,month:9});monthlyReportMonth='2026-09';monthlyReportBuildCurrent();return [facts.find(x=>x.definition.metric_id==='quiz_accuracy_percent').actual.value,document.getElementById('monthlyReportDomains').textContent]});assert.equal(equal[0],50);assert.match(equal[1],/50 %/);assert.match(equal[1],/공통|같은 원본/);
 // Transfer only to existing goal form; no approval or write.
 const draft=host.locator('.card').filter({has:page.locator('h4',{hasText:/^BMI ·/})}).locator('[data-guidance-use]');await draft.click();assert.equal(await page.locator('#goalRegistryForm [name="metric_id"]').inputValue(),'body_bmi');assert.equal(await page.locator('#goalRegistryForm [name="quarter"]').inputValue(),'4');assert.equal(await page.locator('#goalRegistryForm [name="value"]').inputValue(),'25');assert.equal(await page.locator('#goalRegistryApprove').count(),0);
 await page.evaluate(()=>{showView('monthlyReport');monthlyReportBoard='annual';monthlyReportRenderBoard();window.HANI_GOAL_PROGRESS.renderReport()});assert.equal(await page.locator('#annualGoalReport article').count(),9);assert.match(await page.locator('#annualGoalReport').innerText(),/목표/);
 await page.evaluate(()=>{monthlyReportBoard='quarterly';monthlyReportRenderBoard()});await host.scrollIntoViewIfNeeded();assert.ok(await host.evaluate(e=>e.scrollWidth<=e.clientWidth+1));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await host.screenshot({path:path.join(root,'artifacts/report-common',`${width}-${finish}.png`),style:'.ui26-top,#haniContextRemote,.hani-remote-mobile-trigger{visibility:hidden!important}'});
 await page.evaluate(()=>{window.allowed=false;window.HANI_GOAL_PROGRESS.render();monthlyReportBuildCurrent();monthlyReportGenerate('2026-09')});assert.equal(await host.locator('article').count(),0);assert.match(await host.innerText(),/원본 검증 대기/);assert.match(await page.locator('#monthlyReportDomains').textContent(),/원본 검증 대기/);
 assert.deepEqual(await page.evaluate(()=>({state:JSON.stringify(state)===window.beforeState,local:JSON.stringify({...localStorage})===window.beforeLocal,writes:window.writes})),{state:true,local:true,writes:[]});assert.deepEqual(errors,[]);await context.close();
}console.log('PASS report read-only UI 4 combinations: owner gate, nine metrics, month/quarter/annual parity, guidance transfer to existing form without Preview/approval, blocked generate, no state/localStorage writes, overflow. Real auth/PPT/Cloud unverified.');}finally{await browser.close();await new Promise(r=>server.close(r));}
