import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.argv[2]).href);const root=path.resolve(import.meta.dirname,'..');
const server=http.createServer((req,res)=>{const uri=new URL(req.url,'http://test').pathname;const file=path.resolve(root,'.'+(uri==='/'?'/index.html':decodeURIComponent(uri)));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html; charset=utf-8':'application/octet-stream');res.end(fs.readFileSync(file));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({executablePath:process.argv[3],headless:true});const evidence=path.join(root,'qa-evidence');fs.mkdirSync(evidence,{recursive:true});let cases=0;
async function create(raw,{quota=false,readError=false,width=390}={}){const context=await browser.newContext({viewport:{width,height:900},acceptDownloads:true});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await context.addInitScript(({raw,quota,readError})=>{if(!sessionStorage.getItem('synthetic-seeded')){if(raw!==null)localStorage.setItem('hani_os_life_v23',raw);sessionStorage.setItem('synthetic-seeded','1')}const set=Storage.prototype.setItem,get=Storage.prototype.getItem;Storage.prototype.setItem=function(k,v){if(quota&&k.startsWith('hani_os_load_quarantine_'))throw new DOMException('synthetic full','QuotaExceededError');return set.call(this,k,v)};Storage.prototype.getItem=function(k){if(readError&&k==='hani_os_life_v23')throw new Error('synthetic denied');return get.call(this,k)};},{raw,quota,readError});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(origin);await page.waitForLoadState('load');await page.waitForFunction(()=>typeof renderAll==='function');return {context,page,errors};}
try{
 const t=await create(null);const p=t.page;
 const result=await p.evaluate(async()=>{
   const original=localStorage.getItem(STORAGE_KEY);const image='data:image/png;base64,'+'A'.repeat(3*1024*1024);
   for(let i=1;i<=5;i++){const value=freshState();value.books=[{id:'book-'+i,title:'synthetic '+i,cover:image,unknownField:{kept:true}}];if(!await cloudSaveSafetySnapshot('test-'+i,value))throw Error('snapshot failed')}
   const rows=(await safetyArchiveList()).filter(x=>x.verified);
   return {count:rows.length,reasons:rows.map(x=>x.payload.reason),full:rows.every(x=>x.payload.state.books[0].cover===image&&x.payload.state.books[0].unknownField.kept),unchanged:localStorage.getItem(STORAGE_KEY)===original};
 });assert.deepEqual(result,{count:3,reasons:['test-3','test-4','test-5'],full:true,unchanged:true});cases++;
 await p.evaluate(()=>{document.querySelector('#loginGate').style.display='none';document.querySelector('#app').classList.remove('login-locked');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelector('#settings').classList.add('active');document.querySelector('#safetyArchivePanel').open=true;return renderSafetyArchive()});
 assert.equal(await p.locator('#safetyArchiveList button').count(),3);const downloading=p.waitForEvent('download');await p.locator('#safetyArchiveList button').first().click();const downloaded=await (await downloading).path();const exported=JSON.parse(fs.readFileSync(downloaded,'utf8'));assert.equal(exported.books[0].id,'book-5');assert.equal(exported.books[0].cover.length,3*1024*1024+22);await p.locator('#safetyArchivePanel').screenshot({path:path.join(evidence,'backup-history-390.png')});cases++;
 const quota=await p.evaluate(async()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===CLOUD_SAFETY_KEY)throw new DOMException('synthetic full','QuotaExceededError');return set.call(this,k,v)};try{return {ok:await cloudSaveSafetySnapshot('legacy-quota',state),rows:(await safetyArchiveList()).filter(x=>x.verified).length,status:safetyArchiveStatus}}finally{Storage.prototype.setItem=set}});assert.equal(quota.ok,true);assert.equal(quota.rows,3);cases++;
 const denied=await p.evaluate(async()=>{const open=IDBFactory.prototype.open,set=Storage.prototype.setItem;IDBFactory.prototype.open=function(){throw Error('synthetic denied')};try{const fallback=await cloudSaveSafetySnapshot('idb-denied',state);const old=localStorage.getItem(CLOUD_SAFETY_KEY);Storage.prototype.setItem=function(k,v){if(k===CLOUD_SAFETY_KEY)throw new DOMException('synthetic full','QuotaExceededError');return set.call(this,k,v)};const failed=await cloudSaveSafetySnapshot('both-denied',state);return {fallback,failed,oldKept:localStorage.getItem(CLOUD_SAFETY_KEY)===old}}finally{IDBFactory.prototype.open=open;Storage.prototype.setItem=set}});assert.deepEqual(denied,{fallback:true,failed:false,oldKept:true});cases+=2;
 const race=await p.evaluate(async()=>{const snapshot=cloudSaveSafetySnapshot;let unblock;cloudSaveSafetySnapshot=()=>new Promise(resolve=>{unblock=resolve});try{const remote=freshState();remote.books=[{id:'remote-book',title:'remote'}];const pull=cloudApplyRemoteRow({state:remote,revision:99},'').then(()=>false,e=>e.message.includes('Local이 변경'));state.books=[{id:'new-local',title:'new input during backup'}];const saved=save();const raw=localStorage.getItem(STORAGE_KEY);unblock(true);return {rejected:await pull,saved:saved.ok,newInputKept:state.books[0].id==='new-local'&&localStorage.getItem(STORAGE_KEY)===raw}}finally{cloudSaveSafetySnapshot=snapshot}});assert.deepEqual(race,{rejected:true,saved:true,newInputKept:true});cases++;
 assert.deepEqual(t.errors,[]);await t.context.close();console.log('PASS '+cases+' full-runtime backup cases: 3 full copies including 3MB image, download, legacy quota, IndexedDB denial, both fail, concurrent Local input preserved. External requests blocked.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
