import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.argv[2]).href);const root=path.resolve(import.meta.dirname,'..');
const server=http.createServer((req,res)=>{const uri=new URL(req.url,'http://test').pathname;const file=path.resolve(root,'.'+(uri==='/'?'/index.html':decodeURIComponent(uri)));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html; charset=utf-8':'application/octet-stream');res.end(fs.readFileSync(file));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({executablePath:process.argv[3],headless:true});const evidence=path.join(root,'qa-evidence');fs.mkdirSync(evidence,{recursive:true});let cases=0;
async function create(raw,{quota=false,readError=false,width=390}={}){const context=await browser.newContext({viewport:{width,height:900},acceptDownloads:true});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await context.addInitScript(({raw,quota,readError})=>{if(!sessionStorage.getItem('synthetic-seeded')){if(raw!==null)localStorage.setItem('hani_os_life_v23',raw);sessionStorage.setItem('synthetic-seeded','1')}const set=Storage.prototype.setItem,get=Storage.prototype.getItem;Storage.prototype.setItem=function(k,v){if(quota&&k.startsWith('hani_os_load_quarantine_'))throw new DOMException('synthetic full','QuotaExceededError');return set.call(this,k,v)};Storage.prototype.getItem=function(k){if(readError&&k==='hani_os_life_v23')throw new Error('synthetic denied');return get.call(this,k)};},{raw,quota,readError});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(origin);await page.waitForLoadState('load');await page.waitForFunction(()=>typeof renderAll==='function');return {context,page,errors};}
try{
 const initial=await create(null);const clean=await initial.page.evaluate(()=>{const x=freshState();x.accounts=[{id:'synthetic-account',name:'test',openingCash:0}];x.books=Array.from({length:50},(_,i)=>({id:'b'+i,title:'synthetic '+i,unknownFutureField:{kept:true}}));x.unknownFutureField={kept:true};return x});await initial.context.close();
 const nullLists=['travelTrips','travelPlaces','travelWishlist','certificates','wishlistItems','ledgerMonths','spendReviews','investmentMonthlySnapshots','investmentBrokerSnapshots','investmentCashFlows','investmentJournal','investmentWatchlist','campusSemesters'];
 for(const name of nullLists){const raw=JSON.stringify({...clean,[name]:[null]});const t=await create(raw);const result=await t.page.evaluate(async()=>{const original=localStorage.getItem(STORAGE_KEY);const saved=save();let denied=0;for(const f of [()=>writeProtectedState('{}'),()=>removeProtectedState(),()=>cloudApplyRemoteRow({state:freshState(),revision:1},''),()=>cloudPushLocalRow({state:freshState(),revision:1},freshState(),'')])try{await f()}catch(_){denied++}return {active:loadRecovery.active,verified:loadRecovery.verified,unchanged:localStorage.getItem(STORAGE_KEY)===original,saved:saved.ok,denied}});assert.deepEqual(result,{active:true,verified:true,unchanged:true,saved:false,denied:4},name);assert.deepEqual(t.errors,[],name);await t.context.close();cases++;}
 for(const raw of ['{broken','', 'null','[]','42',JSON.stringify({...clean,travelTrips:[{id:'t',itinerary:[null]}]})]){const t=await create(raw);assert.equal(await t.page.evaluate(()=>loadRecovery.active),true);assert.equal(await t.page.evaluate(()=>save().ok),false);assert.equal(await t.page.evaluate(()=>localStorage.getItem(STORAGE_KEY)),raw);assert.deepEqual(t.errors,[]);await t.context.close();cases++;}
 for(const opts of [{quota:true},{readError:true}]){const t=await create('{broken',opts);assert.equal(await t.page.evaluate(()=>loadRecovery.active),true);assert.equal(await t.page.evaluate(()=>save().ok),false);assert.equal(await t.page.evaluate(()=>loadRecovery.verified),false);await t.context.close();cases++;}
 const normal=await create(JSON.stringify(clean));assert.equal(await normal.page.evaluate(()=>save().ok),true);assert.equal(await normal.page.evaluate(()=>state.books.length),50);assert.equal(await normal.page.evaluate(()=>JSON.parse(localStorage.getItem(STORAGE_KEY)).unknownFutureField.kept),true);assert.deepEqual(normal.errors,[]);await normal.context.close();cases++;
 // Full-app recovery UI and actual backup import, no real auth or network.
 for(const width of [1440,390]){const t=await create('{broken',{width});await t.page.evaluate(()=>{document.querySelector('#loginGate').hidden=true;document.querySelector('#loginGate').style.display='none';document.querySelector('#app').classList.remove('login-locked');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelector('#settings').classList.add('active');renderStoragePanel()});assert.ok(await t.page.locator('#loadRecoveryPanel').isVisible());const downloading=t.page.waitForEvent('download');await t.page.locator('#loadRecoveryExport').click();const download=await downloading;const downloaded=await download.path();assert.equal(fs.readFileSync(downloaded,'utf8'),'{broken');await t.page.locator('#loadRecoveryPanel').screenshot({path:path.join(evidence,`load-recovery-${width}.png`)});
 await t.page.locator('#importFile').setInputFiles({name:'synthetic-backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(clean))});await t.page.waitForFunction(()=>!loadRecovery.active);assert.equal(await t.page.evaluate(()=>state.books.length),50);assert.equal(await t.page.evaluate(()=>importSyncHold),true);assert.equal(await t.page.evaluate(()=>localStorage.getItem(loadRecovery.quarantineKey)),'{broken');
 const held=await t.page.evaluate(async()=>{let writes=0;cloudUser={id:'synthetic-owner'};cloudClient={from:()=>{writes++;throw Error('unexpected Cloud')}};cloudAutoSyncReady=true;cloudQueueSync();await cloudSyncCycle();return {writes,hold:importSyncHold,ready:cloudAutoSyncReady}});assert.deepEqual(held,{writes:0,hold:true,ready:false});await t.page.reload();await t.page.waitForFunction(()=>typeof renderAll==='function');assert.equal(await t.page.evaluate(()=>importSyncHold),true);assert.equal(await t.page.evaluate(()=>state.books.length),50);assert.deepEqual(t.errors,[]);await t.context.close();cases++;}
 console.log(`PASS ${cases} full-runtime synthetic cases: null/JSON/root/nested corruption, quota/read denial, normal preservation, 1440/390 recovery/export/import, Cloud hold. No production data or external network.`);
}finally{await browser.close();await new Promise(r=>server.close(r));}
