import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.argv[2]).href);const root=path.resolve(import.meta.dirname,'..');
const server=http.createServer((req,res)=>{const uri=new URL(req.url,'http://test').pathname;const file=path.resolve(root,'.'+(uri==='/'?'/index.html':decodeURIComponent(uri)));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html; charset=utf-8':'application/octet-stream');res.end(fs.readFileSync(file));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({executablePath:process.argv[3],headless:true});const evidence=path.join(root,'qa-evidence');fs.mkdirSync(evidence,{recursive:true});let cases=0;
async function create(raw,{quota=false,readError=false,width=390}={}){const context=await browser.newContext({viewport:{width,height:900},acceptDownloads:true});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await context.addInitScript(({raw,quota,readError})=>{if(!sessionStorage.getItem('synthetic-seeded')){if(raw!==null)localStorage.setItem('hani_os_life_v23',raw);sessionStorage.setItem('synthetic-seeded','1')}const set=Storage.prototype.setItem,get=Storage.prototype.getItem;Storage.prototype.setItem=function(k,v){if(quota&&k.startsWith('hani_os_load_quarantine_'))throw new DOMException('synthetic full','QuotaExceededError');return set.call(this,k,v)};Storage.prototype.getItem=function(k){if(readError&&k==='hani_os_life_v23')throw new Error('synthetic denied');return get.call(this,k)};},{raw,quota,readError});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(origin);await page.waitForLoadState('load');await page.waitForFunction(()=>typeof renderAll==='function');return {context,page,errors};}
try{
 const t=await create(null);const p=t.page;
 const result=await p.evaluate(async()=>{
   const original=localStorage.getItem(STORAGE_KEY);const image='data:image/png;base64,'+'A'.repeat(3*1024*1024);
   for(let i=1;i<=5;i++){const value=freshState();value.books=[{id:'book-'+i,title:'synthetic '+i,cover:image,unknownField:{kept:true}}];if(!await cloudSaveSafetySnapshot('test-'+i,value))throw Error('snapshot failed')}
   const rows=(await safetyArchiveList()).filter(x=>x.verified);
   return {count:rows.length,reasons:rows.map(x=>x.payload.reason),full:rows.every(x=>x.payload.state.books[0].cover===image&&x.payload.state.books[0].unknownField.kept),unchanged:localStorage.getItem(STORAGE_KEY)===original};
 });assert.deepEqual(result,{count:3,reasons:['test-3','test-4','test-5'],full:true,unchanged:true});cases++;
 await p.evaluate(()=>{document.querySelector('#loginGate').style.display='none';document.querySelector('#app').classList.remove('login-locked');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelector('#settings').classList.add('active');document.querySelector('#safetyArchivePanel').open=true;return renderSafetyArchive()});
 assert.equal(await p.locator('#safetyArchiveList button').count(),3);assert.match(await p.locator('#safetyArchiveList button').first().innerText(),/^최신/);assert.match(await p.locator('#safetyArchiveList button').nth(1).innerText(),/^이전 1/);const downloading=p.waitForEvent('download');await p.locator('#safetyArchiveList button').first().click();const downloaded=await (await downloading).path();const exported=JSON.parse(fs.readFileSync(downloaded,'utf8'));assert.equal(exported.books[0].id,'book-5');assert.equal(exported.books[0].cover.length,3*1024*1024+22);await p.locator('#safetyArchivePanel').screenshot({path:path.join(evidence,'backup-history-390.png')});cases++;
 const quota=await p.evaluate(async()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===CLOUD_SAFETY_KEY)throw new DOMException('synthetic full','QuotaExceededError');return set.call(this,k,v)};try{return {ok:await cloudSaveSafetySnapshot('legacy-quota',state),rows:(await safetyArchiveList()).filter(x=>x.verified).length,status:safetyArchiveStatus}}finally{Storage.prototype.setItem=set}});assert.equal(quota.ok,true);assert.equal(quota.rows,3);cases++;
 const denied=await p.evaluate(async()=>{const open=IDBFactory.prototype.open,set=Storage.prototype.setItem;IDBFactory.prototype.open=function(){throw Error('synthetic denied')};try{const fallback=await cloudSaveSafetySnapshot('idb-denied',state);const old=localStorage.getItem(CLOUD_SAFETY_KEY);Storage.prototype.setItem=function(k,v){if(k===CLOUD_SAFETY_KEY)throw new DOMException('synthetic full','QuotaExceededError');return set.call(this,k,v)};const failed=await cloudSaveSafetySnapshot('both-denied',state);return {fallback,failed,oldKept:localStorage.getItem(CLOUD_SAFETY_KEY)===old}}finally{IDBFactory.prototype.open=open;Storage.prototype.setItem=set}});assert.deepEqual(denied,{fallback:true,failed:false,oldKept:true});cases+=2;
 const mismatch=await p.evaluate(async()=>{const before=(await safetyArchiveList()).filter(x=>x.verified).map(x=>x.id),get=IDBObjectStore.prototype.get;IDBObjectStore.prototype.get=function(key){const req=get.call(this,key);if(this.name==='snapshots')Object.defineProperty(req,'result',{get:()=>({payload:{damaged:true}})});return req};try{const fallback=await cloudSaveSafetySnapshot('mismatch',state);const rows=await safetyArchiveList();return {fallback,kept:JSON.stringify(rows.filter(x=>x.verified).map(x=>x.id))===JSON.stringify(before),pending:rows.filter(x=>!x.verified).length}}finally{IDBObjectStore.prototype.get=get}});assert.deepEqual(mismatch,{fallback:true,kept:true,pending:0});cases++;
 const race=await p.evaluate(async()=>{const snapshot=cloudSaveSafetySnapshot;let unblock;cloudSaveSafetySnapshot=()=>new Promise(resolve=>{unblock=resolve});try{const remote=freshState();remote.books=[{id:'remote-book',title:'remote'}];const pull=cloudApplyRemoteRow({state:remote,revision:99},'').then(()=>false,e=>e.message.includes('Local이 변경'));state.books=[{id:'new-local',title:'new input during backup'}];const saved=save();const raw=localStorage.getItem(STORAGE_KEY);unblock(true);return {rejected:await pull,saved:saved.ok,newInputKept:state.books[0].id==='new-local'&&localStorage.getItem(STORAGE_KEY)===raw}}finally{cloudSaveSafetySnapshot=snapshot}});assert.deepEqual(race,{rejected:true,saved:true,newInputKept:true});cases++;
 const pruneFailure=await p.evaluate(async()=>{const remove=IDBObjectStore.prototype.delete;IDBObjectStore.prototype.delete=function(){throw Error('synthetic prune denial')};try{return {ok:await cloudSaveSafetySnapshot('prune-held',state),count:(await safetyArchiveList()).filter(x=>x.verified).length,status:safetyArchiveStatus}}finally{IDBObjectStore.prototype.delete=remove}});assert.equal(pruneFailure.ok,true);assert.equal(pruneFailure.count,4);assert.match(pruneFailure.status,/정리가 보류/);cases++;
 const pullSuccess=await p.evaluate(async()=>{state=freshState();state.books=[{id:'same-book',title:'local before pull',cover:'data:image/png;base64,SYNTHETIC'}];save();const remote=freshState();remote.books=[{id:'same-book',title:'remote after pull',cover:''}];const ok=await cloudApplyRemoteRow({state:remote,revision:11},'');const rows=(await safetyArchiveList()).filter(x=>x.verified).sort((a,b)=>b.id-a.id);return {ok,newTitle:state.books[0].title,coverKept:state.books[0].cover==='data:image/png;base64,SYNTHETIC',fullBefore:rows[0].payload.state.books[0].title==='local before pull'&&rows[0].payload.state.books[0].cover==='data:image/png;base64,SYNTHETIC',readback:JSON.parse(localStorage.getItem(STORAGE_KEY)).books[0].title==='remote after pull'}});assert.deepEqual(pullSuccess,{ok:true,newTitle:'remote after pull',coverKept:true,fullBefore:true,readback:true});cases++;
 const rollback=await p.evaluate(async()=>{const beforeRaw=localStorage.getItem(STORAGE_KEY),before=JSON.stringify(state),set=Storage.prototype.setItem,get=Storage.prototype.getItem;let mismatch=false;Storage.prototype.setItem=function(k,v){const result=set.call(this,k,v);if(k===STORAGE_KEY&&v.includes('synthetic-rollback-target'))mismatch=true;return result};Storage.prototype.getItem=function(k){if(k===STORAGE_KEY&&mismatch){mismatch=false;return 'synthetic readback mismatch'}return get.call(this,k)};try{const remote=freshState();remote.books=[{id:'same-book',title:'synthetic-rollback-target'}];let rejected=false;try{await cloudApplyRemoteRow({state:remote,revision:12},'')}catch(_){rejected=true}return {rejected,rawKept:localStorage.getItem(STORAGE_KEY)===beforeRaw,stateKept:JSON.stringify(state)===before}}finally{Storage.prototype.setItem=set;Storage.prototype.getItem=get}});assert.deepEqual(rollback,{rejected:true,rawKept:true,stateKept:true});cases++;
 const responseRace=await p.evaluate(async()=>{state=freshState();state.books=[{id:'old-local',title:'old'}];save();const local=cloudComparableState(state),remote={revision:1,state:structuredClone(local)};cloudUser={id:'synthetic'};let respond,startedResolve,outgoing;const started=new Promise(r=>startedResolve=r),response=new Promise(r=>respond=r);const query={update:value=>{outgoing=value;return query},eq:()=>query,select:async()=>{startedResolve();return response}};cloudClient={from:()=>query};const pushing=cloudPushLocalRow(remote,local,'synthetic').then(()=>false,()=>true);await started;const imported=freshState();imported.books=[{id:'new-other-tab',title:'new'}];const raw=JSON.stringify(imported);localStorage.setItem(STORAGE_KEY,raw);localStorage.setItem(IMPORT_SYNC_HOLD_KEY,'new-other-tab');respond({data:[{...outgoing,revision:2}],error:null});return {rejected:await pushing,originalKept:localStorage.getItem(STORAGE_KEY)===raw,holdKept:localStorage.getItem(IMPORT_SYNC_HOLD_KEY)==='new-other-tab'}});assert.deepEqual(responseRace,{rejected:true,originalKept:true,holdKept:true});cases++;
 assert.deepEqual(t.errors,[]);await t.context.close();console.log('PASS '+cases+' full-runtime backup cases: 3 full copies including 3MB image, download, legacy quota, IndexedDB denial, both fail, concurrent Local input preserved. External requests blocked.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
