const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),data=require('../hani-character-archive-data.js'),ui=require('../hani-character-archive.js');
const source=fs.readFileSync(path.join(root,'docs/character-bible-m9-mir.md'),'utf8').replace(/\r\n/g,'\n');
assert.equal(data.characters.length,10);assert.equal(data.characters.filter(c=>c.type==='m9_member').length,9);
assert.equal(new Set(data.characters.map(c=>c.id)).size,10);assert.ok(Object.isFrozen(data)&&Object.isFrozen(data.characters[0].sections));
for(const c of data.characters){assert.ok(source.includes(c.canon.replace(/\r\n/g,'\n')),`${c.id} original preserved`);assert.ok(c.axis&&c.tagline&&c.rank);assert.ok(Object.hasOwn(c,'seniority'));if(c.image)assert.ok(fs.existsSync(path.join(root,c.image)),`${c.id} official image`);assert.match(ui.detail(c),/album-spread/);assert.match(ui.detail(c),/함께한 이야기 · 역할/);for(const title of ['처음 만나는 나','알고 보면 이런 성격','일할 때는 또 달라요','성민과 나','멤버들과의 케미','나만의 웃음 포인트','나를 닮은 색과 스타일','소중하게 지키는 것','기억하고 싶은 한마디','캐릭터 설정 원문'])assert.ok(ui.detail(c).includes(title));}
const mir=data.characters.find(c=>c.id==='mir');assert.equal(mir.image,null);assert.equal(mir.type,'ai_entity');assert.equal(mir.status,'SPECIAL MEMBER');assert.match(ui.detail(mir),/hani-staff-mir-v5\.webp/);assert.match(ui.detail(mir),/AI MEMBER/);
for(const c of data.characters){for(const [field,label] of Object.entries({seniority:'SENIORITY',tagline:'TAGLINE',coreIdentity:'CORE IDENTITY'})){const original=c.sections.find(s=>s.label===label);if(original)assert.equal(c[field],original.text,`${c.id} complete ${label}`);}if(c.type==='m9_member')assert.ok(c.areas.length>=3,`${c.id} complete core areas`);}
assert.equal(data.characters.find(c=>c.id==='sooyeon').metadata.proposed.state,'Proposed');
assert.equal(data.characters.find(c=>c.id==='hina').rank,'과장');assert.equal(data.characters.find(c=>c.id==='jieun').rank,'부장');assert.match(data.characters.find(c=>c.id==='hina').seniority,/최고참/);
const html=ui.page();assert.equal((html.match(/data-character-card=/g)||[]).length,10);assert.equal(data.gagBadges.length,10);assert.match(html,/“제가요\?!“|“제가요\?!”/);assert.doesNotMatch(html,/M10|Claude|Codex|Gemini|Muse|Stitch/);
for(const heading of ['M9 + MIR','SUNGMIN × M9 + MIR','RANK &amp; SENIORITY','TEAM DYNAMICS','RUNNING GAG ARCHIVE','CHARACTER RULES','SPECIAL MEMBER','우리의 이야기는 계속돼요'])assert.ok(html.includes(heading)||html.replace(/<[^>]*>/g,'').includes(heading));
// Actual canonical navigation function against a synthetic shell; no app boot/auth/storage.
const main=fs.readFileSync(path.join(root,'hani-main.js'),'utf8'),index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const start=main.indexOf('function showView(id){'),end=main.indexOf('\nconst QUICK_JUMP_ITEMS=',start);assert.ok(start>=0&&end>start);
const nodes=Object.fromEntries(['home','aiTeam','characterArchive','title','desc','pageKicker','app'].map(id=>[id,{textContent:'',classList:{add(){},remove(){}}}]));let hash='',view='';
const document={querySelectorAll:()=>[],querySelector:()=>null,body:{dataset:{}}};const context=vm.createContext({document,$:id=>nodes[id],pageMeta:{characterArchive:['M9 + MIR','Archive','team'],aiTeam:['AI 팀','기존 팀','team']},updateFinishScope(){},setBanner(){},history:{replaceState(_a,_b,h){hash=h}},location:{href:'http://fixture/'},window:{scrollTo(){},HaniAssetMarket:{sync(){}}},cloudUser:null,setTimeout(){},clearTimeout(){},navigationTimer:null,NAVIGATION_VIEWS:new Set(),navigationBooted:false,loginGateUnlocked:false,navigationPersist(){}});
vm.runInContext(main.slice(start,end),context);context.showView('characterArchive');assert.equal(nodes.title.textContent,'M9 + MIR');assert.equal(document.body.dataset.view,'characterArchive');assert.equal(hash,'#characterArchive');context.showView('aiTeam');assert.equal(document.body.dataset.view,'aiTeam');
assert.equal((index.match(/id="characterArchive"/g)||[]).length,1);assert.equal((index.match(/data-view="characterArchive"/g)||[]).length,1);assert.ok(index.includes('id="teamList"')&&index.includes('id="teamProfilePanel"'));
for(const file of ['hani-character-archive.js','hani-character-archive-data.js'])assert.doesNotMatch(fs.readFileSync(path.join(root,file),'utf8'),/localStorage|sessionStorage|cloudClient|fetch\(|\.from\(|\.setItem\(/);
console.log('PASS: Canon originals, 9 M9 + MIR, official assets, frozen read-only registry, all detail sections, rank/seniority, Proposed metadata, approved MIR avatar / original AI identity, canonical navigation round-trip, original team anchors.');
