import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.argv[2]).href);const root=path.resolve(import.meta.dirname,'..');
const server=http.createServer((req,res)=>{const uri=new URL(req.url,'http://test').pathname;const file=path.resolve(root,'.'+(uri==='/'?'/index.html':decodeURIComponent(uri)));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html; charset=utf-8':'application/octet-stream');res.end(fs.readFileSync(file));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({executablePath:process.argv[3],headless:true});const evidence=path.join(root,'qa-evidence');fs.mkdirSync(evidence,{recursive:true});let cases=0;
async function create(raw,{quota=false,readError=false,width=390}={}){const context=await browser.newContext({viewport:{width,height:900},acceptDownloads:true});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await context.addInitScript(({raw,quota,readError})=>{if(!sessionStorage.getItem('synthetic-seeded')){if(raw!==null)localStorage.setItem('hani_os_life_v23',raw);sessionStorage.setItem('synthetic-seeded','1')}const set=Storage.prototype.setItem,get=Storage.prototype.getItem;Storage.prototype.setItem=function(k,v){if(quota&&k.startsWith('hani_os_load_quarantine_'))throw new DOMException('synthetic full','QuotaExceededError');return set.call(this,k,v)};Storage.prototype.getItem=function(k){if(readError&&k==='hani_os_life_v23')throw new Error('synthetic denied');return get.call(this,k)};},{raw,quota,readError});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(origin);await page.waitForLoadState('load');await page.waitForFunction(()=>typeof renderAll==='function');return {context,page,errors};}
try{
 for(const width of [390,1440]){const t=await create(null,{width}),p=t.page;
 assert.ok(await p.locator('#loginGate').isVisible());assert.match(await p.locator('#loginGateStatus').innerText(),/연결 도구|불러오지/);assert.equal(await p.evaluate(()=>document.body.classList.contains('login-scroll-locked')),true);cases++;
 await p.setViewportSize({width,height:360});await p.evaluate(()=>showLoginRecoveryGate());const box=await p.locator('.login-card').boundingBox();assert.ok(box.y>=0,'short viewport form top reachable');assert.equal(await p.locator('#loginGate').evaluate(x=>getComputedStyle(x).overscrollBehavior),'contain');await p.locator('#loginGateRecoverySave').scrollIntoViewIfNeeded();const submitBox=await p.locator('#loginGateRecoverySave').boundingBox();assert.ok(submitBox.y>=0&&submitBox.y+submitBox.height<=360);await p.locator('#loginGate').screenshot({path:path.join(evidence,'login-short-'+width+'.png')});cases++;
 await p.evaluate(()=>{unlockLoginGate();document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelector('#investment').classList.add('active');document.querySelectorAll('#investment .panel').forEach(x=>x.classList.remove('active'));document.querySelector('#investOverview').classList.add('active');document.querySelector('#investOverviewAll').classList.add('active')});assert.equal(await p.evaluate(()=>document.body.classList.contains('login-scroll-locked')),false);
 const hint=p.locator('#brokerLatestHoldingRows').locator('xpath=ancestor::div[contains(@class,"tw")]/preceding-sibling::p');assert.equal(await hint.isVisible(),width===390);const wrapper=p.locator('#brokerLatestHoldingRows').locator('xpath=ancestor::div[contains(@class,"tw")]');assert.equal(await wrapper.getAttribute('tabindex'),'0');if(width===390){const bounds=await wrapper.evaluate(x=>({scroll:x.scrollWidth,client:x.clientWidth}));assert.ok(bounds.scroll>bounds.client);await wrapper.focus();await p.keyboard.press('ArrowRight');await p.waitForTimeout(200);assert.ok(await wrapper.evaluate(x=>x.scrollLeft>0));}await p.setViewportSize({width,height:900});await p.waitForFunction(()=>getComputedStyle(document.querySelector('#loginGate')).opacity==='0');await wrapper.scrollIntoViewIfNeeded();await p.locator('#brokerLatestHoldingRows').locator('xpath=ancestor::div[contains(@class,"card")][1]').screenshot({path:path.join(evidence,'investment-table-'+width+'.png')});cases++;
 assert.deepEqual(t.errors,[]);await t.context.close();}
 console.log('PASS '+cases+' UI cases: missing SDK notice/login protection, short viewport login reachability/scroll lock, mobile table hint/keyboard horizontal scrolling. Actual Android keyboard remains unverified.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
