import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import {renderSeed,buildSeed,seedPath,runtimePath} from "./hani-relationship-seed-build.mjs";

const seed=JSON.parse(fs.readFileSync(seedPath,"utf8"));
assert.equal(seed.people.length,18);
assert.equal(seed.relations.length,57);
const ids=new Set(seed.people.map(p=>p.id));
for(const r of seed.relations){assert.ok(ids.has(r.a)&&ids.has(r.b));assert.ok(r.score>=0&&r.score<=100)}
const runtime=fs.readFileSync(runtimePath,"utf8"),context=vm.createContext({});
vm.runInContext(runtime,context);
assert.ok(Object.isFrozen(context.HaniRelationshipSeed));
assert.deepEqual(JSON.parse(JSON.stringify(context.HaniRelationshipSeed)),seed);
assert.equal(renderSeed(seed),runtime);
assert.equal(buildSeed(true),runtime,"--check uses identical generated bytes without writing");
assert.throws(()=>renderSeed({...seed,relations:[{a:"absent",b:"hani",score:90}]}),/Invalid relation/);
assert.throws(()=>renderSeed({...seed,people:[seed.people[0],seed.people[0]]}),/unique ids/);
const escaped=renderSeed({...seed,source:'</script><img onerror="x">&\u2028\u2029'});
assert.ok(!/[<>&\u2028\u2029]/.test(escaped));
vm.runInContext(escaped,context);
assert.equal(context.HaniRelationshipSeed.source,'</script><img onerror="x">&\u2028\u2029');
const index=fs.readFileSync(new URL("../index.html",import.meta.url),"utf8");
const seedScript=index.match(/<script src="\.\/hani-relationship-seed\.js\?v=([^"]+)"><\/script>/);
const boardScript=index.match(/<script src="\.\/hani-board\.js\?v=([^"]+)"><\/script>/);
assert.ok(seedScript&&boardScript,"both runtime scripts must exist");
assert.ok(seedScript.index<boardScript.index,"seed loads before board");
assert.equal(seedScript[1],boardScript[1],"match current cache pattern; train owns future bumps");
console.log("PASS: approved 18 people/57 relations, generated runtime, --check, id validation, escaping/load order");
