const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),data=require('../hani-character-archive-data.js'),ui=require('../hani-character-archive.js');
const source=fs.readFileSync(path.join(root,'docs/character-bible-m9-mir.md'),'utf8').replace(/\r\n/g,'\n');
assert.equal(data.characters.length,10);assert.equal(data.characters.filter(c=>c.type==='m9_member').length,9);
assert.equal(new Set(data.characters.map(c=>c.id)).size,10);assert.ok(Object.isFrozen(data)&&Object.isFrozen(data.characters[0].sections));
for(const c of data.characters){assert.ok(source.includes(c.canon.replace(/\r\n/g,'\n')),`${c.id} original preserved`);assert.ok(c.axis&&c.tagline&&c.rank);assert.ok(Object.hasOwn(c,'seniority'));if(c.image)assert.ok(fs.existsSync(path.join(root,c.image)),`${c.id} official image`);assert.match(ui.detail(c),/Rank · 직급/);assert.match(ui.detail(c),/Seniority · 연차/);for(const title of ['OVERVIEW','PERSONALITY','WORK STYLE','SEONGMIN','M9 RELATIONSHIPS','RUNNING GAGS','VISUAL','BOUNDARY','QUOTES','CANON ORIGINAL'])assert.ok(ui.detail(c).includes(title));}
const mir=data.characters.find(c=>c.id==='mir');assert.equal(mir.image,null);assert.equal(mir.type,'ai_entity');assert.equal(mir.status,'SPECIAL MEMBER');assert.doesNotMatch(ui.detail(mir),/<img/);assert.match(ui.detail(mir),/AI ENTITY/);
for(const c of data.characters){for(const [field,label] of Object.entries({seniority:'SENIORITY',tagline:'TAGLINE',coreIdentity:'CORE IDENTITY'})){const original=c.sections.find(s=>s.label===label);if(original)assert.equal(c[field],original.text,`${c.id} complete ${label}`);}if(c.type==='m9_member')assert.ok(c.areas.length>=3,`${c.id} complete core areas`);}
assert.equal(data.characters.find(c=>c.id==='sooyeon').metadata.proposed.state,'Proposed');
assert.equal(data.characters.find(c=>c.id==='hina').rank,'과장');assert.equal(data.characters.find(c=>c.id==='jieun').rank,'부장');assert.match(data.characters.find(c=>c.id==='hina').seniority,/최고참/);
const html=ui.page();assert.equal((html.match(/data-character-card=/g)||[]).length,10);assert.equal(data.gagBadges.length,10);assert.match(html,/“제가요\?!“|“제가요\?!”/);assert.doesNotMatch(html,/M10|Claude|Codex|Gemini|Muse|Stitch/);
for(const heading of ['M9 + MIR','SEONGMIN × M9 + MIR','RANK &amp; SENIORITY','TEAM DYNAMICS','RUNNING GAG ARCHIVE','CHARACTER RULES','SPECIAL MEMBER','CHARACTER ESSENCE'])assert.ok(html.includes(heading)||html.replace(/<[^>]*>/g,'').includes(heading));
// Actual canonical navigation function against a synthetic shell; no app boot/auth/storage.
const main=fs.readFileSync(path.join(root,'hani-main.js'),'utf8'),index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const start=main.indexOf('function showView(id){'),end=main.indexOf('\nconst QUICK_JUMP_ITEMS=',start);assert.ok(start>=0&&end>start);
const nodes=Object.fromEntries(['home','aiTeam','characterArchive','title','desc','pageKicker','app'].map(id=>[id,{textContent:'',classList:{add(){},remove(){}}}]));let hash='',view='';
const document={querySelectorAll:()=>[],querySelector:()=>null,body:{dataset:{}}};const context=vm.createContext({document,$:id=>nodes[id],pageMeta:{characterArchive:['M9 + MIR','Archive','team'],aiTeam:['AI 팀','기존 팀','team']},updateFinishScope(){},setBanner(){},history:{replaceState(_a,_b,h){hash=h}},location:{href:'http://fixture/'},window:{scrollTo(){},HaniAssetMarket:{sync(){}}},cloudUser:null,setTimeout(){}});
vm.runInContext(main.slice(start,end),context);context.showView('characterArchive');assert.equal(nodes.title.textContent,'M9 + MIR');assert.equal(document.body.dataset.view,'characterArchive');assert.equal(hash,'#characterArchive');context.showView('aiTeam');assert.equal(document.body.dataset.view,'aiTeam');
assert.equal((index.match(/id="characterArchive"/g)||[]).length,1);assert.equal((index.match(/data-view="characterArchive"/g)||[]).length,1);assert.ok(index.includes('id="teamList"')&&index.includes('id="teamProfilePanel"'));
for(const file of ['hani-character-archive.js','hani-character-archive-data.js'])assert.doesNotMatch(fs.readFileSync(path.join(root,file),'utf8'),/localStorage|sessionStorage|cloudClient|fetch\(|\.from\(|\.setItem\(/);
console.log('PASS: Canon originals, 9 M9 + MIR, official assets, frozen read-only registry, all detail sections, rank/seniority, Proposed metadata, no human MIR, canonical navigation round-trip, original team anchors.');
