const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');const root=path.resolve(__dirname,'..');
(async()=>{const server=http.createServer((req,res)=>{const p=new URL(req.url,'http://local').pathname,file=path.resolve(root,'.'+(p==='/'?'/index.html':decodeURIComponent(p)));if(!file.startsWith(root+path.sep)||!/^\/(index\.html|hani-[a-zA-Z0-9._-]+\.(js|css)|assets\/[^.][a-zA-Z0-9./_-]+\.(png|webp|jpg|svg|json))$/.test(p==='/'?'/index.html':p)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.webp')?'image/webp':file.endsWith('.png')?'image/png':file.endsWith('.jpg')?'image/jpeg':file.endsWith('.svg')?'image/svg+xml':'application/json');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;let browser;const output=path.join(root,'artifacts/character-archive');fs.mkdirSync(output,{recursive:true});const results=[];
try{browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});for(const width of [1440,390]){const context=await browser.newContext({viewport:{width,height:900}});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.waitForSelector('#characterArchiveContent[data-mounted="true"]',{state:'attached'});
// Disposable empty browser only. UI gate revealed solely for fixture navigation; no auth or live data.
await page.evaluate(()=>{document.querySelector('#loginGate')?.style.setProperty('display','none','important');document.querySelector('#app').classList.remove('login-locked');document.querySelector('#app').setAttribute('aria-hidden','false');window.archiveStateBefore=JSON.stringify(state);window.archiveStorageBefore=JSON.stringify({...localStorage});});
if(width===390)await page.locator('#mobileMenu').click();await page.locator('.nav-btn[data-view="characterArchive"]').click();await page.waitForSelector('#characterArchive.active');assert.equal(await page.locator('#characterArchive [data-character-card]').count(),10);await page.locator('.ca-grid [data-character-profile="mir"]').click();assert.equal(await page.locator('#caDetailTitle').textContent(),'미르');assert.equal(await page.locator('#caDetail img').count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
await page.locator('#characterArchive').screenshot({path:path.join(output,`${width}-os-integration.png`)});
if(width===390)await page.locator('#mobileMenu').click();await page.locator('.nav-btn[data-view="aiTeam"]').click();await page.waitForSelector('#aiTeam.active');assert.equal(await page.locator('#teamList [data-team-key]').count(),9);assert.equal(await page.locator('#teamProfilePanel').isVisible(),true);
await page.evaluate(()=>showView('settings'));assert.equal(await page.locator('#settings').isVisible(),true);await page.evaluate(()=>showView('characterArchive'));assert.equal(await page.locator('#characterArchiveContent').getAttribute('data-mounted'),'true');
assert.deepEqual(await page.evaluate(()=>({stateSame:JSON.stringify(state)===window.archiveStateBefore,storageSame:JSON.stringify({...localStorage})===window.archiveStorageBefore})),{stateSame:true,storageSame:true});assert.deepEqual(errors,[]);results.push({width,archive:true,originalTeam:9,settings:true,stateSame:true,storageSame:true,consoleErrors:errors,cloud:'External requests blocked; no authenticated testing'});await context.close();}fs.writeFileSync(path.join(output,'integration-qa.json'),JSON.stringify({results,scope:'Actual OS empty disposable browser; no login or cloud'},null,2));console.log('PASS: actual OS 1440/390 Archive ↔ existing team/settings, 9 original members, no duplicate mount/state/storage mutations, no JS errors.');}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
