import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
import {stripTypeScriptTypes} from 'node:module';
import {sha256,modularRuntimeText,canonicalPackageHash,evaluatePackage} from './hani-one-pass-rules.mjs';
import {isTextArtifact} from './hani-runtime-closure.mjs';
import contract from '../dev-center/one-pass-gate-contract.json' with {type:'json'};
const root=new URL('../',import.meta.url),base=execFileSync('git',['rev-parse','90b7440'],{encoding:'utf8'}).trim(),candidate='b'.repeat(40);
const html=fs.readFileSync(new URL('index.html',root),'utf8');
const paths=['index.html',...[...html.matchAll(/(?:src|href)=["']([^"']+\.(?:js|css)(?:\?[^"']*)?)["']/g)].map(m=>m[1]).filter(p=>!/^https?:|^\/\//.test(p)).map(p=>p.replace(/^\.\//,'').split('?')[0])];
const map=new Map([...new Set(paths)].map(p=>[p,fs.readFileSync(new URL(p,root),'utf8')]));
const baselineMap=new Map([...map.keys()].map(p=>[p,execFileSync('git',['show',`${base}:${p}`],{encoding:'utf8',maxBuffer:10*1024*1024})]));
const runtime=modularRuntimeText(map),baselineRuntime=modularRuntimeText(baselineMap),files=[...map].map(([path,content])=>({path,content,encoding:'utf8'})),packageHash=canonicalPackageHash(files).package_sha256;
const evidence={version:1,status:'PASS',base_sha:base,candidate_sha:candidate,runtime_sha256:sha256(runtime),baseline_runtime_sha256:sha256(baselineRuntime),package_sha256:packageHash,tests:Object.entries({protected_runtime:28,backup_runtime:11,access_ui:6,transaction_runtime:1,owner_handlers:2,storage_gate_negative:19}).map(([id,cases])=>({id,cases,status:'PASS',test_sha256:sha256('synthetic'),output_sha256:sha256('synthetic')}))};
const evidenceText=JSON.stringify(evidence),policy={version:1,approval:'OWNER_REVIEWED',approval_id:'SYNTHETIC_NOT_AUTHORIZATION',base_sha:base,source_candidate_sha:candidate,runtime_sha256:sha256(runtime),baseline_runtime_sha256:sha256(baselineRuntime),package_sha256:packageHash,evidence_sha256:sha256(evidenceText),expires_at:'2099-01-01T00:00:00Z'};
const raw=fs.readFileSync(new URL('supabase/functions/hani-deploy-bridge/index.ts',root),'utf8'),source=stripTypeScriptTypes(raw).replace(/^import .*;\r?\n/gm,'');
const env={};const ctx={isTextArtifact,console,crypto,TextEncoder,TextDecoder,URL,Response,Request,Headers,atob,btoa,setTimeout,clearTimeout,Deno:{env:{get:key=>env[key]},serve:()=>{}},createClient:()=>{},fetch:()=>{throw Error('Unexpected external request')}};
vm.createContext(ctx);vm.runInContext(source,ctx);ctx.syntheticBase=base;
vm.runInContext('getMainRef=async()=>({object:{sha:syntheticBase}});listOpenPullRequests=async()=>[];',ctx);
const options={mainTextOverride:baselineRuntime,qaProfile:'HINA_RELEASE_GATE_v0.2_MULTI_FILE',protectedPackageHash:packageHash};
const check=(r,id)=>r.checks.find(x=>x.id===id)?.status;
let result=await ctx.runHinaReleaseQa(runtime,'synthetic',base,options);assert.equal(check(result,'PROTECTED_WRITE_SURFACE'),'FAIL','missing policy keeps default block');
env.HANI_PROTECTED_WRITE_APPROVAL=JSON.stringify(policy);env.HANI_PROTECTED_WRITE_EVIDENCE=evidenceText;
result=await ctx.runHinaReleaseQa(runtime,'synthetic',base,options);if(check(result,'PROTECTED_WRITE_SURFACE')!=='PASS')console.log(result.checks.filter(x=>x.id.includes('PROTECTED')));assert.equal(check(result,'PROTECTED_WRITE_SURFACE'),'PASS');assert.equal(check(result,'PROTECTED_PRESERVATION_CONTRACT'),'PASS');
result=await ctx.runHinaReleaseQa(runtime+'\n/* tampered */','synthetic',base,options);assert.equal(check(result,'PROTECTED_WRITE_SURFACE'),'FAIL');
result=await ctx.runHinaReleaseQa(runtime,'synthetic','c'.repeat(40),options);assert.equal(check(result,'MAIN_SHA_STABLE'),'FAIL');assert.equal(result.ok,false,'contract does not bypass other gates');
result=await ctx.runHinaReleaseQa(runtime,'synthetic',base,{...options,protectedPackageHash:sha256('asset changed')});assert.equal(check(result,'PROTECTED_WRITE_SURFACE'),'FAIL');
result=await ctx.runHinaReleaseQa(runtime,'synthetic',base,{...options,qaProfile:'legacy'});assert.equal(check(result,'PROTECTED_WRITE_SURFACE'),'FAIL');
const pkg={files,base_main_sha:base,candidate_sha:candidate,package_sha256:packageHash};
const baseFiles=[...baselineMap.values()].join('\n');
let local=evaluatePackage({pkg,baseFiles,productionVersion:'2.9.178',contract});assert.equal(check(local,'protected_write_surface'),'BLOCKED');
local=evaluatePackage({pkg,baseFiles,productionVersion:'2.9.178',contract,protectedApproval:{policy,evidenceText,baselineRuntimeText:baselineRuntime}});assert.equal(check(local,'protected_write_surface'),'PASS');
local=evaluatePackage({pkg:{...pkg,candidate_sha:'c'.repeat(40)},baseFiles,productionVersion:'2.9.178',contract,protectedApproval:{policy,evidenceText,baselineRuntimeText:baselineRuntime}});assert.equal(check(local,'protected_write_surface'),'BLOCKED');
assert.equal(sha256(modularRuntimeText(map)),sha256([html,...ctx.localStylePaths(html).map(p=>map.get(p)),...ctx.localScriptPaths(html).map(p=>map.get(p))].join('\n/* HANI MODULAR RUNTIME BOUNDARY */\n')),'Node/server runtime hash format identical');
ctx.syntheticBaseline=baselineRuntime;vm.runInContext('githubRuntimeCombined=async()=>({runtimeText:syntheticBaseline});',ctx);
let supplied=await ctx.runSuppliedModularQa(files,'synthetic',base);assert.equal(check(supplied,'PROTECTED_WRITE_SURFACE'),'PASS');
const encoded=files.map(f=>({...f,encoding:'base64',content:Buffer.from(f.content).toString('base64')}));supplied=await ctx.runSuppliedModularQa(encoded,'synthetic',base);assert.equal(check(supplied,'PROTECTED_WRITE_SURFACE'),'PASS','base64 decoded content matches exact approved bytes');
assert.equal(supplied.candidate_sha256,sha256(runtime));
console.log('PASS 12 integration cases: actual server/local gates default block, exact synthetic policy, source/package/commit drift, legacy rejection, other gates retained, runtime hash parity, utf8/base64 supplied package equivalence. No real policy or external effects.');
